Cat vs Dog classification app | Vladislav Shalnev
vladyoslav/spbu-ml pull request #1
Opened 2022-12-06 02:16 UTC by vladyoslav

Знаю, что получилось достаточно просто, но это единственная моделька, которую удалось запустить 😞 (некоторые просто не хотели запускаться, другим не хватало видеопамяти)

Протестить можно тут https://vladyoslav-spbu-ml.streamlit.app/

2022-12-06 15:12 UTC, SpirinEgor requested changes
It is okay to use a small dummy classification model. I suggest trying another one, but you can continue to work with the current. Despite this, there is a lot of work to clean up code and make it more reliable and reusable. Also, don't forget about style-guide and `pep8`, I suggest using `black` formatted to automatically reformat your code.

2022-12-06 15:12 UTC, SpirinEgor commented on app.py
> +from huggingface_hub import from_pretrained_keras
It seems that this is not the right way to use models. In [documentation](https://huggingface.co/docs/huggingface_hub/index) said that this is the package for creators and collaborators.

2022-12-06 15:12 UTC, SpirinEgor commented on app.py
> +model = from_pretrained_keras("carlosaguayo/cats_vs_dogs")
Oh, maybe you need to use this library because of keras 🙃
Did you try this model https://huggingface.co/facebook/convnext-tiny-224? It is a little bit bigger but can classify more than 2 classes (1k if I remember correctly).

2022-12-06 15:12 UTC, SpirinEgor commented on app.py
> +    return message
Well, it is nice that you can copy code from another source 👍 But as a home task, I would like to see what can you do by yourself.

2022-12-06 15:12 UTC, SpirinEgor commented on app.py
> +)
This is not a good idea to define your model and UI in the global scope. Moreover, do it in one file. This makes all of your code hard to reuse and extend. Move model initialization and interface building in separate function/classes and make sure that all starts from the entry point (`if __name__ == "__main__"`)

2022-12-06 15:12 UTC, SpirinEgor commented on packages.txt
> +python3-opencv
Dummy coping never ends well 🙃 Do you know why this file is here? For OpenCV, you only need to install the PIP package, which already contains all binaries.

Btw, you need OpenCV only to resize images. But this package is big and holds valuable memory. Maybe you will try to resize the image without it? You can use NumPy/torch to crop or directly resize image.

2022-12-06 15:12 UTC, SpirinEgor commented on requirements.txt
> +transformers
Usually, it's better to add `~=<version>` for packages. Sometimes updates are not backwards compatible so they can crash the app.

2022-12-14 01:24 UTC, vladyoslav commented on app.py
> +)
Done!

2022-12-14 01:24 UTC, vladyoslav commented on requirements.txt
> +transformers
Done!

2022-12-14 16:05 UTC, SpirinEgor reviewed
A small suggestion about processing results. Everything else is perfect 👍

2022-12-14 16:05 UTC, SpirinEgor commented on classifier.py
> +        )
```python
results = [dict.fromkeys([item["label"]], item["score"]) for item in raw_results]
```

In this way it becomes more readable

2022-12-14 16:19 UTC, vladyoslav commented on classifier.py
> +        )
Done!

2022-12-20 09:25 UTC, SpirinEgor approved these changes
👍

2022-12-25 15:20 UTC, merged